"""Intial User/Admin/Researcher model migration with pw hashing

Revision ID: 1a0d41c7d2e9
Revises: None
Create Date: 2016-11-15 21:02:20.087039

"""

# revision identifiers, used by Alembic.
revision = '1a0d41c7d2e9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('UCID', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('pw_hash', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UCID')
    )
    op.create_index('ix_USER_first_name', 'USER', ['first_name'], unique=False)
    op.create_index('ix_USER_last_name', 'USER', ['last_name'], unique=False)
    op.create_table('ADMIN',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UCID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UCID'], ['USER.UCID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('RESEARCHER',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UCID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UCID'], ['USER.UCID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RESEARCHER')
    op.drop_table('ADMIN')
    op.drop_index('ix_USER_last_name', 'USER')
    op.drop_index('ix_USER_first_name', 'USER')
    op.drop_table('USER')
    ### end Alembic commands ###
