"""empty message

Revision ID: 1b750411a029
Revises: 3a74462fc9bc
Create Date: 2017-05-30 14:23:52.609690

"""

# revision identifiers, used by Alembic.
revision = '1b750411a029'
down_revision = '3a74462fc9bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PUBLICATION',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UCID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('submit_date', sa.DateTime(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('pdf', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['UCID'], ['USER.UCID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PUBLICATION')
    ### end Alembic commands ###
