"""updated User constructor

Revision ID: 1e3dcae6af3a
Revises: 3e08657b3a1d
Create Date: 2016-11-27 20:39:02.458000

"""

# revision identifiers, used by Alembic.
revision = '1e3dcae6af3a'
down_revision = '3e08657b3a1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
