"""Added News Item Data Table

Revision ID: 205dd40b792d
Revises: 42883162604e
Create Date: 2017-02-02 16:41:58.723359

"""

# revision identifiers, used by Alembic.
revision = '205dd40b792d'
down_revision = '42883162604e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NEWS_ITEM',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UCID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('submit_date', sa.DateTime(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['UCID'], ['USER.UCID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NEWS_ITEM')
    ### end Alembic commands ###
