"""User Model helper functions

Revision ID: 240c6e5d6d21
Revises: 1a0d41c7d2e9
Create Date: 2016-11-17 15:39:36.000483

"""

# revision identifiers, used by Alembic.
revision = '240c6e5d6d21'
down_revision = '1a0d41c7d2e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
