"""empty message

Revision ID: 26296a0b8f16
Revises: 59eea360a2d4
Create Date: 2017-06-15 16:57:20.972309

"""

# revision identifiers, used by Alembic.
revision = '26296a0b8f16'
down_revision = '59eea360a2d4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PUBLICATION', sa.Column('pdf_name', sa.Text(), nullable=False))
    op.add_column('PUBLICATION', sa.Column('pdf_url', sa.Text(), nullable=False))
    op.drop_column('PUBLICATION', 'pdf')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PUBLICATION', sa.Column('pdf', postgresql.BYTEA(), nullable=False))
    op.drop_column('PUBLICATION', 'pdf_url')
    op.drop_column('PUBLICATION', 'pdf_name')
    ### end Alembic commands ###
