"""1

Revision ID: 280934e2c01e
Revises: 240c6e5d6d21
Create Date: 2016-11-17 15:56:49.418100

"""

# revision identifiers, used by Alembic.
revision = '280934e2c01e'
down_revision = '240c6e5d6d21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
