"""Updated Person model to have a caption field

Revision ID: 2b02ccd5d017
Revises: 580f73372e3
Create Date: 2017-07-24 09:31:07.744933

"""

# revision identifiers, used by Alembic.
revision = '2b02ccd5d017'
down_revision = '580f73372e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PERSON', sa.Column('caption', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PERSON', 'caption')
    ### end Alembic commands ###
