"""updated publication structure

Revision ID: 2be31ba6b3ab
Revises: 26296a0b8f16
Create Date: 2017-07-03 16:37:51.551255

"""

# revision identifiers, used by Alembic.
revision = '2be31ba6b3ab'
down_revision = '26296a0b8f16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
