"""Adding a position and alumni field to Person table

Revision ID: 349314394abf
Revises: 756353e68cc
Create Date: 2017-08-25 11:11:22.712463

"""

# revision identifiers, used by Alembic.
revision = '349314394abf'
down_revision = '756353e68cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PERSON', sa.Column('alumni', sa.Boolean(), nullable=False, server_default='f'))
    op.add_column('PERSON', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PERSON', 'position')
    op.drop_column('PERSON', 'alumni')
    ### end Alembic commands ###
