"""Slight change to Funding Account

Revision ID: 36d32e051ed4
Revises: 4be14ef5fa4c
Create Date: 2016-12-09 11:28:46.575792

"""

# revision identifiers, used by Alembic.
revision = '36d32e051ed4'
down_revision = '4be14ef5fa4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
