"""empty message

Revision ID: 3a74462fc9bc
Revises: 205dd40b792d
Create Date: 2017-03-30 20:27:54.788121

"""

# revision identifiers, used by Alembic.
revision = '3a74462fc9bc'
down_revision = '205dd40b792d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FUNDING_ACCOUNT')
    op.drop_table('LOG_ENTRY')
    op.add_column('USER', sa.Column('lab', sa.String(length=64), nullable=True))
    op.create_index('ix_USER_lab', 'USER', ['lab'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_USER_lab', 'USER')
    op.drop_column('USER', 'lab')
    op.create_table('LOG_ENTRY',
    sa.Column('ID', sa.INTEGER(), server_default='nextval(\'"LOG_ENTRY_ID_seq"\'::regclass)', nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('UCID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['UCID'], [u'USER.UCID'], name=u'LOG_ENTRY_UCID_fkey'),
    sa.PrimaryKeyConstraint('ID', name=u'LOG_ENTRY_pkey')
    )
    op.create_table('FUNDING_ACCOUNT',
    sa.Column('ID', sa.INTEGER(), server_default='nextval(\'"FUNDING_ACCOUNT_ID_seq"\'::regclass)', nullable=False),
    sa.Column('acc_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('acc_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('acc_other', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('RSC_ID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['RSC_ID'], [u'USER.UCID'], name=u'FUNDING_ACCOUNT_RSC_ID_fkey'),
    sa.PrimaryKeyConstraint('ID', name=u'FUNDING_ACCOUNT_pkey')
    )
    ### end Alembic commands ###
