"""Role table and User methods

Revision ID: 3c49bdc7f5c4
Revises: None
Create Date: 2016-12-04 19:31:11.504904

"""

# revision identifiers, used by Alembic.
revision = '3c49bdc7f5c4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('REPORT',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('file_loc', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('ROLE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_ROLE_default', 'ROLE', ['default'], unique=False)
    op.create_table('USER',
    sa.Column('UCID', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('pw_hash', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('email_conf', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ROLE.id'], ),
    sa.PrimaryKeyConstraint('UCID')
    )
    op.create_index('ix_USER_first_name', 'USER', ['first_name'], unique=False)
    op.create_index('ix_USER_last_name', 'USER', ['last_name'], unique=False)
    op.create_table('FUNDING_ACCOUNT',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('acc_no', sa.String(length=64), nullable=False),
    sa.Column('acc_name', sa.String(length=64), nullable=False),
    sa.Column('acc_type', sa.String(length=64), nullable=True),
    sa.Column('RSC_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RSC_ID'], ['USER.UCID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('ix_FUNDING_ACCOUNT_acc_no', 'FUNDING_ACCOUNT', ['acc_no'], unique=False)
    op.create_table('WORK_ORDER',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('no_samples', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('ri_qehf', sa.Boolean(), nullable=True),
    sa.Column('ri_qeb', sa.Boolean(), nullable=True),
    sa.Column('ri_tsq', sa.Boolean(), nullable=True),
    sa.Column('ri_unk', sa.Boolean(), nullable=True),
    sa.Column('tm_pep', sa.Boolean(), nullable=True),
    sa.Column('tm_fa', sa.Boolean(), nullable=True),
    sa.Column('tm_aa', sa.Boolean(), nullable=True),
    sa.Column('tm_unk', sa.Boolean(), nullable=True),
    sa.Column('RPT_ID', sa.Integer(), nullable=True),
    sa.Column('RSC_ID', sa.Integer(), nullable=False),
    sa.Column('ADM_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ADM_ID'], ['USER.UCID'], ),
    sa.ForeignKeyConstraint(['RPT_ID'], ['REPORT.ID'], ),
    sa.ForeignKeyConstraint(['RSC_ID'], ['USER.UCID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('LOG_ENTRY',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('UCID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UCID'], ['USER.UCID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LOG_ENTRY')
    op.drop_table('WORK_ORDER')
    op.drop_index('ix_FUNDING_ACCOUNT_acc_no', 'FUNDING_ACCOUNT')
    op.drop_table('FUNDING_ACCOUNT')
    op.drop_index('ix_USER_last_name', 'USER')
    op.drop_index('ix_USER_first_name', 'USER')
    op.drop_table('USER')
    op.drop_index('ix_ROLE_default', 'ROLE')
    op.drop_table('ROLE')
    op.drop_table('REPORT')
    ### end Alembic commands ###
