"""Email Confirmation methods

Revision ID: 3e08657b3a1d
Revises: 36db3c9ca6ba
Create Date: 2016-11-26 15:16:08.725000

"""

# revision identifiers, used by Alembic.
revision = '3e08657b3a1d'
down_revision = '36db3c9ca6ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
