"""Additions: FA, WO, REPORT, LE

Revision ID: 43665c586f3e
Revises: 355c44928029
Create Date: 2016-11-23 12:01:01.212515

"""

# revision identifiers, used by Alembic.
revision = '43665c586f3e'
down_revision = '355c44928029'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
