"""added submit_date field to WorkOrder

Revision ID: 44db936c78be
Revises: 3c49bdc7f5c4
Create Date: 2016-12-04 21:56:28.265252

"""

# revision identifiers, used by Alembic.
revision = '44db936c78be'
down_revision = '3c49bdc7f5c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WORK_ORDER', sa.Column('submit_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WORK_ORDER', 'submit_date')
    ### end Alembic commands ###
