"""Added an optional Image field to News Items

Revision ID: 4e51f99ae5e8
Revises: 2b02ccd5d017
Create Date: 2017-07-25 12:55:25.582972

"""

# revision identifiers, used by Alembic.
revision = '4e51f99ae5e8'
down_revision = '2b02ccd5d017'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NEWS_ITEM', sa.Column('image', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NEWS_ITEM', 'image')
    ### end Alembic commands ###
