"""Added the Person model

Revision ID: 580f73372e3
Revises: 32c8c1a19e1c
Create Date: 2017-07-21 15:26:40.926524

"""

# revision identifiers, used by Alembic.
revision = '580f73372e3'
down_revision = '32c8c1a19e1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PERSON',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UCID', sa.Integer(), nullable=False),
    sa.Column('submit_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('photo_name', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['UCID'], ['USER.UCID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PERSON')
    ### end Alembic commands ###
