"""empty message

Revision ID: 59eea360a2d4
Revises: 1b750411a029
Create Date: 2017-06-14 14:57:31.449988

"""

# revision identifiers, used by Alembic.
revision = '59eea360a2d4'
down_revision = '1b750411a029'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
