"""Changed Report balance to Numeric type

Revision ID: 756353e68cc
Revises: 786b6e9ff0c
Create Date: 2017-08-14 15:48:45.308003

"""

# revision identifiers, used by Alembic.
revision = '756353e68cc'
down_revision = '786b6e9ff0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "REPORT" ALTER COLUMN balance TYPE NUMERIC')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "REPORT" ALTER COLUMN balance TYPE INTEGER')
    ### end Alembic commands ###
