"""Updated the NewsItem title column type to a larger varchar

Revision ID: 786b6e9ff0c
Revises: 4e51f99ae5e8
Create Date: 2017-07-27 14:50:37.065321

"""

# revision identifiers, used by Alembic.
revision = '786b6e9ff0c'
down_revision = '4e51f99ae5e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "NEWS_ITEM" ALTER COLUMN title TYPE VARCHAR(300)')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "NEWS_ITEM", ALTER COLUMN title TYPE VARCHAR(64)')
    ### end Alembic commands ###
