"""Updated User model to support logins

Revision ID: bbc289eccf4
Revises: 280934e2c01e
Create Date: 2016-11-17 16:57:40.127951

"""

# revision identifiers, used by Alembic.
revision = 'bbc289eccf4'
down_revision = '280934e2c01e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
